require:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
#   DisabledByDefault: true

# Style/HashSyntax:
#   Enabled: true

## Custom settings according to the current codebase
Lint/MissingSuper:
  AllowedParentClasses:
    - Rackup::Server


## Won't change without breaking changes or major refactoring
Style/OptionalBooleanParameter:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StderrPuts:
  Enabled: false


## It's not really necessary to address about these
Style/ModuleFunction:
  Severity: warning

Style/MultipleComparison:
  Severity: warning

Style/RescueStandardError:
  Severity: warning

Style/SpecialGlobalVars:
  Severity: warning


## We should address these eventually
Style/CaseEquality:
  Exclude:
    - padrino-core/lib/padrino-core/filter.rb
    - padrino-core/lib/padrino-core/path_router/compiler.rb

Style/CombinableLoops:
  Exclude:
    - padrino-gen/lib/padrino-gen/padrino-tasks/mongoid.rb

Style/Encoding:
  Exclude:
    - padrino-admin/padrino-admin.gemspec
    - padrino-cache/padrino-cache.gemspec
    - padrino-gen/lib/padrino-gen/generators/project/config.ru
    - padrino-gen/padrino-gen.gemspec
    - padrino-helpers/padrino-helpers.gemspec
    - padrino-mailer/padrino-mailer.gemspec
    - padrino-performance/padrino-performance.gemspec
    - padrino-support/padrino-support.gemspec
    - padrino/padrino.gemspec

Style/EvalWithLocation:
  Exclude:
    - padrino-core/lib/padrino-core/cli/base.rb

Lint/SendWithMixinArgument:
  Exclude:
    - padrino-performance/lib/suites/json.rb

Lint/ScriptPermission:
  Exclude:
    - padrino-admin/padrino-admin.gemspec
    - padrino-cache/padrino-cache.gemspec
    - padrino-gen/lib/padrino-gen/generators/project/config.ru
    - padrino-gen/padrino-gen.gemspec
    - padrino-helpers/padrino-helpers.gemspec
    - padrino-mailer/padrino-mailer.gemspec
    - padrino-performance/padrino-performance.gemspec
    - padrino-support/padrino-support.gemspec
    - padrino/padrino.gemspec

Lint/RescueException:
  Exclude:
    - padrino-core/lib/padrino-core/application/routing.rb
    - padrino-core/lib/padrino-core/loader.rb
    - padrino-core/lib/padrino-core/reloader.rb

Lint/IneffectiveAccessModifier:
  Exclude:
    - padrino-core/lib/padrino-core/cli/base.rb
    - padrino-core/lib/padrino-core/cli/launcher.rb
    - padrino-helpers/lib/padrino-helpers/form_builder/abstract_form_builder.rb

Lint/ShadowedException:
  Exclude:
    - padrino-core/lib/padrino-core/cli/binstub.rb

Lint/UselessMethodDefinition:
  Exclude:
    - padrino-core/test/fixtures/apps/mountable_apps/rack_apps.rb


## Tests exclusions
Naming/FileName:
  Exclude:
    - '**/test/**/*'

Style/GlobalVars:
  Exclude:
    - '**/test/**/*'

Lint/RaiseException:
  Exclude:
    - '**/test/**/*'

Lint/EmptyFile:
  Exclude:
    - '**/test/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - '**/test/**/*'
