require 'rubygems'
require 'rake'
require 'sdoc'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "padrino-core"
    gem.summary = "The required Padrino core gem"
    gem.description = "The Padrino core gem required for use of this framework"
    gem.email = "padrinorb@gmail.com"
    gem.homepage = "http://github.com/padrino/padrino-framework/tree/master/padrino-core"
    gem.authors = ["Padrino Team", "Nathan Esquenazi", "Davide D'Agostino", "Arthur Chiu"]
    gem.executables = ["padrino"]
    gem.rubyforge_project = 'padrino-core'
    gem.add_runtime_dependency     "sinatra",       ">= 0.9.4"
    gem.add_runtime_dependency     "i18n",          ">= 0.3.2"
    gem.add_runtime_dependency     "usher",         ">= 0.6.2"
    gem.add_runtime_dependency     "thor",          ">= 0.13.0"
    gem.add_runtime_dependency     "bundler",       ">= 0.9.3"
    gem.add_development_dependency "shoulda",       ">= 0"
    gem.add_development_dependency "mocha",         ">= 0.9.7"
    gem.add_development_dependency "rack-test",     ">= 0.5.0"
    gem.add_development_dependency "webrat",        ">= 0.5.1"
    # gem is a Gem::Specification... see http://www.rubygems.org/read/chapter/20 for additional settings
  end
  Jeweler::GemcutterTasks.new
  Jeweler::RubyforgeTasks.new { |r| r.doc_task = :none }
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: sudo gem install jeweler"
end

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

begin
  require 'rcov/rcovtask'
  Rcov::RcovTask.new do |test|
    test.libs << 'test'
    test.pattern = 'test/**/test_*.rb'
    test.verbose = true
  end
rescue LoadError
  task :rcov do
    abort "RCov is not available. In order to run rcov, you must: sudo gem install spicycode-rcov"
  end
end

task :test => :check_dependencies

task :default => :test

require 'rake/rdoctask'
Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "padrino-core #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
