require 'rubygems'
require 'rake'
require File.expand_path("../../padrino-core/lib/padrino-core/version.rb", __FILE__)

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "padrino-admin"
    gem.summary = "Admin Dashboard for Padrino"
    gem.description = "Admin View for Padrino applications"
    gem.email = "padrinorb@gmail.com"
    gem.homepage = "http://github.com/padrino/padrino-framework/tree/master/padrino-admin"
    gem.authors = ["Padrino Team", "Nathan Esquenazi", "Davide D'Agostino", "Arthur Chiu"]
    gem.rubyforge_project = 'padrino-admin'
    gem.version = Padrino.version
    gem.add_runtime_dependency     "padrino-core",    "= #{Padrino.version}"
    gem.add_runtime_dependency     "padrino-gen",     "= #{Padrino.version}"
    gem.add_runtime_dependency     "padrino-helpers", "= #{Padrino.version}"
    gem.add_development_dependency "haml",            ">= 2.2.1"
    gem.add_development_dependency "shoulda",         ">= 0"
    gem.add_development_dependency "mocha",           ">= 0.9.7"
    gem.add_development_dependency "rack-test",       ">= 0.5.0"
    gem.add_development_dependency "webrat",          ">= 0.5.1"
    # gem is a Gem::Specification... see http://www.rubygems.org/read/chapter/20 for additional settings
  end
  Jeweler::GemcutterTasks.new
  Jeweler::RubyforgeTasks.new { |r| r.doc_task = :none }
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: sudo gem install jeweler"
end

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'test'

  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

begin
  require 'rcov/rcovtask'
  Rcov::RcovTask.new do |rcov|
    rcov.libs << 'test'
    rcov.pattern = 'test/**/test_*.rb'
    rcov.verbose = true
    rcov.rcov_opts << ['--exclude /Gems/1.8/gems/,padrino-core,padrino-cache,padrino-gen,padrino-helpers,padrino-mailer']
  end
rescue LoadError
  task :rcov do
    abort "RCov is not available. In order to run rcov, you must: sudo gem install relevance-rcov"
  end
end

task :default => :test