# coding:utf-8
require 'rubygems'
require 'rubygems/specification'
require 'rake'

def gemspec
  @gemspec ||= begin
    gem_name =  File.basename(File.dirname(__FILE__))
    file = File.expand_path("../#{gem_name}.gemspec", __FILE__)
    eval(File.read(file), binding, file)
  end
end

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

begin
  require 'rake/gempackagetask'
rescue LoadError
  task(:gem) { $stderr.puts '`gem install rake` to package gems' }
else
  Rake::GemPackageTask.new(gemspec) do |pkg|
    pkg.gem_spec = gemspec
  end
  task :gem => :gemspec
end

desc "install the gem locally"
task :install => :package do
  sh %{gem install pkg/#{gemspec.name}-#{gemspec.version}}
end

desc "validate the gemspec"
task :gemspec do
  gemspec.validate
end

desc "Release the gem"
task :release => :package do
  system "gem push pkg/#{gemspec.name}-#{gemspec.version}.gem"
end

task :package => :gemspec
task :default => :test