# AUTOGENERATED FILE -- Don't change this file unless you know what you are doing! 
PADRINO_ROOT = File.dirname(__FILE__) + '/..' unless defined? PADRINO_ROOT
require 'padrino-core'
require 'padrino-mailer'
require 'padrino-routing'
Padrino.load!