clear_sources
source 'http://gemcutter.org'

# Project requirements
gem 'sinatra', :require_as => 'sinatra/base'
gem 'padrino'
gem 'rack-flash'

# Component requirements

# Testing requirements
gem 'rack-test', :require_as => 'rack/test', :only => :testing