# AUTOGENERATED FILE -- Don't change this file unless you know what you are doing! 
PADRINO_ROOT = File.dirname(__FILE__) + '/..' unless defined? PADRINO_ROOT

# Try to load the vendorized padrino.
Dir[PADRINO_ROOT + "/vendor/padrino/**/lib"].each do |gem|
  $LOAD_PATH.unshift gem
end

require 'padrino'
Padrino.load!