require 'rubygems'
require 'rake'
require File.expand_path("../../padrino-core/lib/padrino-core/version.rb", __FILE__)

subgems = [
  ["padrino-core", "= #{Padrino.version}"],
  ["padrino-helpers", "= #{Padrino.version}"],
  ["padrino-mailer", "= #{Padrino.version}"],
  ["padrino-gen", "= #{Padrino.version}"],
  ["padrino-admin", "= #{Padrino.version}"]
  # ["padrino-cache", "= #{Padrino.version}"],
]

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "padrino"
    gem.summary = "The Godfather of Sinatra"
    gem.description = "The Godfather of Sinatra provides a full-stack agnostic framework on top of Sinatra"
    gem.email = "padrinorb@gmail.com"
    gem.homepage = "http://github.com/padrino/padrino-framework"
    gem.authors = ["Padrino Team", "Nathan Esquenazi", "Davide D'Agostino", "Arthur Chiu"]
    gem.rubyforge_project = 'padrino'
    gem.add_development_dependency "haml",          ">= 2.2.1"
    gem.add_development_dependency "shoulda",       ">= 2.10.3"
    gem.add_development_dependency "mocha",         ">= 0.9.7"
    gem.add_development_dependency "rack-test",     ">= 0.5.0"
    gem.add_development_dependency "webrat",        ">= 0.5.1"
    subgems.each { |subgem_data| gem.add_runtime_dependency *subgem_data }
    # gem is a Gem::Specification... see http://www.rubygems.org/read/chapter/20 for additional settings
  end
  Jeweler::GemcutterTasks.new
  Jeweler::RubyforgeTasks.new { |r| r.doc_task = :none }
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: sudo gem install jeweler"
end

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

begin
  require 'rcov/rcovtask'
  Rcov::RcovTask.new do |test|
    test.libs << 'test'
    test.pattern = 'test/**/test_*.rb'
    test.verbose = true
  end
rescue LoadError
  task :rcov do
    abort "RCov is not available. In order to run rcov, you must: sudo gem install relevance-rcov"
  end
end

task :default => :test

require 'rake/rdoctask'
Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "padrino #{Padrino.version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

########### CUSTOM TASKS ##########

task :build => "lib/padrino.rb"

desc "Create padrino.rb"
task "lib/padrino.rb" do
  mkdir_p "lib"
  File.open("lib/padrino.rb","w+") do |file|
    file.puts "### AUTOMATICALLY GENERATED. DO NOT EDIT!"
    subgems.each do |pair|
      g, _ = pair
      file.puts "require '#{g}'" unless g =~ /padrino-gen/
    end
  end
end